import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";

import Toast from "../../../components/UI/Toast/Toast";
import { categoriesService } from "../../../services/categoriesService";

import styles from "./categories.module.css";

export default function AddCategory(): React.JSX.Element {
  const navigate = useNavigate();

  // Create a ref for the toast dialog to control its visibility and manage toast messages and types
  const toastRef = useRef<HTMLDialogElement>(
    null,
  ) as React.RefObject<HTMLDialogElement>;

  const [toastMessage, setToastMessage] = useState("");
  const [toastType, setToastType] = useState<"success" | "error">("success");

  // showToast function displays the toast message for a short duration.
    const showToast = () => {
    if (toastRef.current) {
      toastRef.current.showModal();
      setTimeout(() => {
        toastRef.current?.close();
      }, 3000);
    }
  };

  // Handle the form submission for adding a new category. This function collects the form data, generates a slug from the category name, and calls the categoriesService to create the new category. It also manages toast messages for success or error feedback.
  const handleSubmit = async (
    e: React.SyntheticEvent<HTMLFormElement>,
  ): Promise<void> => {
    e.preventDefault();

    const formData = new FormData(e.currentTarget);

    // Extract the category name and image URL from the form data. The slug is generated by converting the name to lowercase, trimming whitespace, and replacing spaces with hyphens.
    const name = formData.get("name") as string;
    const imageUrl = formData.get("imageUrl") as string;
    const slug = name.toLowerCase().trim().replace(/\s+/g, "-");

    // Validate that the category name and image URL are provided. If either is missing, show an error toast message and return early.
    if (!name || !imageUrl) {
      setToastMessage("Please provide both name and image URL.");
      setToastType("error");
      showToast();
      return;
    }
    // Attempt to create the new category using the categoriesService. If successful, show a success toast message, reset the form, and navigate to the categories list page after a short delay. If there's an error during creation, show an error toast message.
    try {
      const form = e.currentTarget;
      await categoriesService.createCategory(name, slug, imageUrl);

      setToastMessage("Category created successfully");
      setToastType("success");
      showToast();

      form.reset();

      // Navigate to the categories list page after a short delay to allow the user to see the success message. This provides a better user experience by confirming the action before redirecting.
      setTimeout(() => {
        navigate("/admin/categories");
      }, 1500);
    } catch (error: unknown) {
      // Handle errors during category creation. If there's an error, show an error toast message.
      const errorMessage =
        error instanceof Error ? error.message : "Failed to create category";
      setToastMessage(errorMessage);
      setToastType("error");
      showToast();
    }
  };

  return (
    <>
      <Toast ref={toastRef} message={toastMessage} type={toastType} />

      <div className={styles.formContainer}>
        <h1 className={styles.title}>Add New Category</h1>

        <form className={styles.form} onSubmit={handleSubmit}>
          <div className={styles.formGroup}>
            <label htmlFor="name">Category Name</label>

            <input
              type="text"
              id="name"
              name="name"
              placeholder="Enter category name"
              required
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="imageUrl">Image URL</label>

            <input
              type="text"
              id="imageUrl"
              name="imageUrl"
              placeholder="https://..."
              required
            />
          </div>

          <button type="submit" className={styles.submitButton}>
            Add Category
          </button>
        </form>
      </div>
    </>
  );
}
