import { useRef, useState, useEffect } from "react";
import { useNavigate, useParams, type Params } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import Toast from "../../../components/UI/Toast/Toast";
import Spinner from "../../../components/UI/Spinner/Spinner";
import { categoriesService } from "../../../services/categoriesService";

import styles from "./categories.module.css";

interface CategoryResponse {
  message: string;
  category: {
    name: string;
    slug: string;
    imageUrl: string;
  };
}

export default function EditCategory(): React.JSX.Element {
  const navigate = useNavigate();
  // Get the categoryId from the URL parameters using useParams hook
  const params = useParams() as Params<string>;

  // Create a ref for the toast dialog to control its visibility and manage toast messages and types
  const toastRef = useRef<HTMLDialogElement>(
    null,
  ) as React.RefObject<HTMLDialogElement>;

  const [toastMessage, setToastMessage] = useState("");
  const [toastType, setToastType] = useState<"success" | "error">("success");

  // State variables to hold the category name and image URL for editing
  const [name, setName] = useState("");
  const [imageUrl, setImageUrl] = useState("");

  // Use react-query to fetch the category details by ID. The query is enabled only if the categoryId is present in the URL parameters. The fetched data is used to populate the form fields for editing.
  const { data, isLoading, error } = useQuery({
    queryKey: ["category", params.categoryId],
    queryFn: async () => {
      const response = await categoriesService.getById(params.categoryId!);
      const { category } = response as CategoryResponse;
      return category;
    },
    enabled: !!params.categoryId,
  });

  // showToast function displays the toast message for a short duration.
  const showToast = () => {
    if (toastRef.current) {
      toastRef.current.showModal();
      setTimeout(() => {
        toastRef.current?.close();
      }, 3000);
    }
  };

  // Use useEffect to update the form fields with the fetched category data when it becomes available. This ensures that the form is pre-filled with the current category details for editing.
  useEffect(() => {
    if (!data) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setName(data.name);
    setImageUrl(data.imageUrl);
  }, [data]);

  // Handle the form submission for updating the category. This function collects the form data, generates a slug from the category name, and calls the categoriesService to update the category. It also manages toast messages for success or error feedback.
  const handleSubmit = async (
    e: React.FormEvent<HTMLFormElement>,
  ): Promise<void> => {
    e.preventDefault();

    // Extract the category name and image URL from the form data. The slug is generated by converting the name to lowercase, trimming whitespace, and replacing spaces with hyphens.
    const slug = name.toLowerCase().trim().replace(/\s+/g, "-");

    // Validate that the category name and image URL are provided. If either is missing, show an error toast message and return early.
    if (!name || !imageUrl) {
      setToastMessage("Please provide both name and image URL.");
      setToastType("error");
      showToast();
      return;
    }
    // Attempt to update the category using the categoriesService. If successful, show a success toast message and navigate to the categories list page after a short delay. If there's an error during the update, show an error toast message.
    try {
      await categoriesService.updateCategory(
        params.categoryId!,
        name,
        slug,
        imageUrl,
      );

      setToastMessage("Category updated successfully");
      setToastType("success");
      showToast();

      // Navigate to the categories list page after a short delay to allow the user to see the success message. This provides a better user experience by confirming the action before redirecting.
      setTimeout(() => {
        navigate("/admin/categories");
      }, 1500);
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to update category";

      setToastMessage(errorMessage);
      setToastType("error");
      showToast();
    }
  };

  if (isLoading) {
    return <Spinner />;
  }

  if (error) {
    return <p>Error: {(error as Error).message}</p>;
  }

  return (
    <>
      <Toast ref={toastRef} message={toastMessage} type={toastType} />

      <div className={styles.formContainer}>
        <h1 className={styles.title}>Edit Category</h1>

        <form className={styles.form} onSubmit={handleSubmit}>
          <div className={styles.formGroup}>
            <label htmlFor="name">Category Name</label>

            <input
              type="text"
              id="name"
              name="name"
              placeholder="Enter category name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
            />
          </div>

          <div className={styles.formGroup}>
            <label htmlFor="imageUrl">Image URL</label>

            <input
              type="text"
              id="imageUrl"
              name="imageUrl"
              placeholder="https://..."
              value={imageUrl}
              onChange={(e) => setImageUrl(e.target.value)}
              required
            />
          </div>

          <button type="submit" className={styles.submitButton}>
            Update Category
          </button>
        </form>
      </div>
    </>
  );
}
